### ISSUE TITLE
🐞 Bug - Support Belfius `v24.3.1`

### ISSUE THREAD

**Issue by Rikj000** [Rikj000/Belfius-Root#2]
## Issue Description
With the update of Belfius `v24.3.1` the name-space of the root check function changed.

Which breaks the XPosed hook of this module.

## Work Around
Downgrade to Belfius `v24.1.0`

## ToDo
- [x] Add helper to `getPackageVersion` of Belfius
- [x] Add helper to `findAndHookRootCheck` methods
- [x] Add hook for the new name-space
- [x] Keep support for the old name-space
